services:
  bandeco:
    image: ghcr.io/jonascardoso/bandeco-unicamp:develop
    container_name: bandeco-unicamp-develop
    init: true
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - runtime-cache-develop:/bandeco/.cache_bandeco_nutricao

volumes:
  runtime-cache-develop:
