# Ruff configuration for Bandeco-Unicamp project
target-version = "py312"
line-length = 120

[lint]
select = ["E", "F", "W", "I", "B"]

ignore = [
    "E501",
    "E402",
]

[lint.isort]
known-first-party = [
    "bandeco",
    "comando",
    "config",
    "cardapio",
    "util",
    "log",
    "servico",
]